### ISSUE TITLE
Looking forward to the pre-trained model 

### ISSUE THREAD

**Issue by zhhongzhi** [ag1988/injecting_numeracy#1]
Very interesting work! I'm wondering when the pre-trained model would be kindly released.

**Comment by ag1988** [comment]
Thanks for your interest in our code! We plan on releasing it somewhere
around June 15 & are sorry for the delay.

**Comment by nrjvarshney** [comment]
@ag1988 Would you be able to share the code for textual data generation?
if that's not possible then maybe just the vocabulary for template instantiation?

**Comment by mega002** [comment]
@nrjvarshney we've just published the code for textual data generation:
https://github.com/ag1988/injecting_numeracy/tree/master/textual_data_generation

**Comment by masashi-y** [comment]
Hi, I'd love to have the pre-trained model, too! Any update on the release?

**Comment by ag1988** [comment]
Hi Masashi,

Apologies for the delay...will try to upload in 2-3 days.

Best,
Ankit

**Comment by ag1988** [comment]
Hey! The complete code is up now including the data & trained models.
