### ISSUE TITLE
pretrained model checkpoint

### ISSUE THREAD

**Issue by bhuthesh** [ag1988/injecting_numeracy#5]
Hi, 

I want to initialize my model with GENBERT weights and run few experiments. If you allow the pretrained model to be downloaded, where can I download it from? 

Thank you,

**Comment by bhuthesh** [comment]
Sorry didn't see the `download.sh` script which does it. Closing the issue.

**Comment by ag1988** [comment]
Hi,

You can view the download and usage instructions at
https://github.com/ag1988/injecting_numeracy/tree/master/pre_training.
Hope this helps.

Regarding, the licensing question I don't think we need to add one. Feel
free to use our code and models...a citation to our paper will suffice.

Thanks,
Ankit
