### ISSUE TITLE
Arguments for Textual Data generation

### ISSUE THREAD

**Issue by nitishgupta** [ag1988/injecting_numeracy#6]
What are the arguments to `textual_data_generation/generate_examples.py` for re-creating the textual data used in the paper?

**Comment by mega002** [comment]
Hi @nitishgupta , the textual synthetic data used in the paper was created by running the following command:
```
$ python scripts/generate_examples.py --domain mixed \
--num_passages 100000 --num_eval_examples 10000  \
--min_num_sentences 3 --max_num_sentences 6 \
--used_values_prob 0.7 \
--output_file_base raw_data/synthetic_textual_mixed_min3_max6_up0.7
```
This will create two `json` files of training and development examples:
```
synthetic_textual_mixed_min3_max6_up0.7_dev.json
synthetic_textual_mixed_min3_max6_up0.7_train.json
```
It should take about 2-3 minutes. There's some randomization in the generation process, if you need the exact same files we used, please let me know.
