### ISSUE TITLE
Digit tokenization 

### ISSUE THREAD

**Issue by mianzg** [ag1988/injecting_numeracy#7]
Hi Ankit, in the paper "digit tokenization" was implemented but I cannot follow how this is done in the script. I had a quick search in `finetune_on_drop.py`, the argumentt `indiv_digits` is commented out. Could you help point this part out in the code? Thanks a lot!

**Comment by ag1988** [comment]
Hi Mian, thanks for your interest in our work! Implementation of the "digit tokenization" can be viewed at `pre_training/gen_train_data_MLM.py`. It basically first uses [BertTokenizer](https://github.com/ag1988/injecting_numeracy/blob/d69ce33b7ccf0265dfeecf429cfe9ac9a2f1c8f9/pre_training/gen_train_data_MLM.py#L187) to obtain wordpieces and then further splits these individual wordpieces using [split_digits()](https://github.com/ag1988/injecting_numeracy/blob/d69ce33b7ccf0265dfeecf429cfe9ac9a2f1c8f9/pre_training/gen_train_data_MLM.py#L146). 

--indiv_digits is commented out in the finetuning script as we first we create features using `pre_training/gen_bert/create_examples_n_features.py` which already contain tokenized text - the finetuning script then simply uses them and doesn't call the tokenizer itself.

Hope this helps!
